# -*- coding: utf-8 -*-
"""hotel_billing_system.ipynb.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_HG_VeVDljAVEXc3MRp4HFwLQ1T1LxK
"""

# Hotel Billing System Project

import datetime       # Import datetime module for showing current date and time
import random         # Import random module to generate random bill numbers

print("=================Welcome to Makki's Hotel========================")
print("Here is our menu")

# Dictionary to store menu items with their prices
menu={"Tea" :        400,
      "Coffee" :     650,
      "Pizza" :      2000,
      "Burger" :     850,
      "Sandwich":    900,
      "Fries" :      400,
      "Cold_Drink" : 200,
      "Ice_Cream" :  370,
      "Water"  :     300

      }

# Display menu items with prices
for item, price in menu.items():
  print(f" {item} : RS = {price}")

# Initialize empty order list and total amount
order_list = []
total_amount = 0

# Loop for taking orders
while True:
 order=input("Select the food you want to order:").title()  # Taking food name input and converting to Title Case
 if order in menu:   # Check if order is in menu
  quantity=int(input(f"How many {order} do you want?:"))   # Ask user for quantity
  cost= menu[order] * quantity   # Calculate cost = price * quantity
  total_amount += cost           # Add cost to total amount
  order_list.append ((order, quantity, cost))  # Save order details in list
  print(f"Your {order} has been added in order:")

 else:
  print("Invalid order")   # If user enters wrong item

 order_more = input("Do you want to order more thing's?  (Y/N):").lower() # Ask user if they want to order more
 if order_more != "y":   # If answer is not 'y', stop loop
  break

print("====================Service Tax======================")
service_tax= total_amount * 0.03   # 3% service tax
final_amount=  total_amount + service_tax   # Final amount after adding tax

print("==========================Final Bill=====================")
bill_time= datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")  # Current date and time in string format
bill_number= random.randint(1000,9999)  # Random 4-digit bill number
print(f"Bill generated on :  {bill_time}")
print(f"Bill number : BILL - {bill_number}")

# Display order list
for item, quantity, cost in order_list:
  print(f"{item} x {quantity} : RS = {cost}")

print("-----------------------------------------------------------")
print (f"Your Total amount : RS = {total_amount}")   # Show total amount before tax
print (f" Your Service tax : RS = {service_tax:.2f}") # Show service tax with 2 decimal points
print(f"Your Final amount : RS = {final_amount:.2f}") # Show final payable amount
print("-----------------------------------------------------------")